<h1>MACHINE LEARNING<h1>

<P> ML predicts future or solve problems on the basis of past (data). <br> 
It finds hidden patterns and relationship to solve problems. <br>
ML learns algorithm patterns based on examples of the task. <br> 
PARTITION IN THE ML:- <BR> 
1. Supervised learning ---> a. Classification b. Regression <br> y= target variable or dependent variable or label , x= feature or independent variable. <br> y is always single and x can be multiple. <br> 
2. Unsupervised learning. <br>

In [262]:
# feautre / variable /column are same.

In [263]:
import pandas as pd
import numpy as np

In [264]:
df=pd.read_csv("Used_Bikes.csv")
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,First Owner,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,First Owner,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,First Owner,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,First Owner,13.0,150.0,Bajaj

In [265]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32648 entries, 0 to 32647
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   bike_name   32648 non-null  object
 1   price       32648 non-null  float64
 2   city        32648 non-null  object
 3   kms_driven  32648 non-null  float64
 4   owner       32648 non-null  object
 5   age         32648 non-null  float64
 6   power       32648 non-null  float64
 7   brand       32648 non-null  object
dtypes: float64(4), object(4)
memory usage: 2.0+ MB

In [266]:
df.drop_duplicates(inplace=True)

In [267]:
df.isnull().sum()

bike_name     0
price         0
city          0
kms_driven    0
owner         0
age           0
power         0
brand         0
dtype: int64

In [268]:
df["brand"].value_counts()>=10

brand
Bajaj               True
Royal Enfield       True
Hero                True
Honda               True
Yamaha              True
TVS                 True
KTM                 True
Suzuki              True
Harley-Davidson     True
Kawasaki            True
Hyosung             True
Mahindra            True
Benelli             True
Triumph             True
Ducati              True
BMW                 True
Jawa               False
Indian             False
MV                 False
Rajdoot            False
LML                False
Yezdi              False
Ideal              False
Name: count, dtype: bool

In [269]:
df.brand.value_counts().keys()
brand_list=['Bajaj', 'Royal Enfield', 'Hero', 'Honda', 'Yamaha', 'TVS', 'KTM',
       'Suzuki', 'Harley-Davidson', 'Kawasaki', 'Hyosung', 'Mahindra',
       'Benelli', 'Triumph', 'Ducati', 'BMW']

In [270]:
filter_brand=df[df["brand"].isin(brand_list)]
filter_brand

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj

In [271]:
# y=price , x=other columns 
# ML predicts price (y) on the basis of other columns (x).
# Price is in continuous nature i.e Regression.

In [272]:
categorical=df.select_dtypes(include="O")
categorical

,bike_name,city,owner,brand
0,TVS Star City Plus Dual Tone 110cc,Ahmedabad,First Owner,TVS
1,Royal Enfield Classic 350cc,Delhi,First Owner,Royal Enfield
2,Triumph Daytona 675R,Delhi,First Owner,Triumph
3,TVS Apache RTR 180cc,Bangalore,First Owner,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,Bangalore,First Owner,Yamaha
...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,Delhi,First Owner,Hero
9369,Bajaj Avenger 220cc,Bangalore,First Owner,Bajaj
9370,Harley-Davidson Street 750 ABS,Jodhpur,First Owner,Harley-Davidson
9371,Bajaj Dominar 400 ABS,Hyderabad,First Owner,Bajaj
9372,Bajaj Avenger Street 220,Hyderabad,First Owner,Bajaj

In [273]:
numerical=df.select_dtypes(exclude="O")
numerical

         price  kms_driven  age  power
0      35000.0     17654.0  3.0  110.0
1     119900.0     11000.0  4.0  350.0
2     600000.0       110.0  8.0  675.0
3      65000.0     16329.0  4.0  180.0
4      80000.0     10000.0  3.0  150.0
...        ...         ...  ...    ...
9362   25000.0     48587.0  8.0  150.0
9369   35000.0     60000.0  9.0  220.0
9370  450000.0      3430.0  4.0  750.0
9371  139000.0     21300.0  4.0  400.0
9372   80000.0      7127.0  5.0  220.0

[7324 rows x 4 columns]

In [274]:
# ML algorithm cannot accept alphabetical data.
categorical["owner"].value_counts()

owner
First Owner             6642
Second Owner             588
Third Owner               84
Fourth Owner Or More      10
Name: count, dtype: int64

In [275]:
dt={"First Owner" :1,"Second Owner":2,"Third Owner" :3,"Fourth Owner Or More":4 }
categorical["owner"]=categorical["owner"].map(dt)

In [276]:
brand_list

['Bajaj',
 'Royal Enfield',
 'Hero',
 'Honda',
 'Yamaha',
 'TVS',
 'KTM',
 'Suzuki',
 'Harley-Davidson',
 'Kawasaki',
 'Hyosung',
 'Mahindra',
 'Benelli',
 'Triumph',
 'Ducati',
 'BMW']

In [277]:
dt2= {item:i for i,item in enumerate(brand_list,start=1)}
dt2

{'Bajaj': 1,
 'Royal Enfield': 2,
 'Hero': 3,
 'Honda': 4,
 'Yamaha': 5,
 'TVS': 6,
 'KTM': 7,
 'Suzuki': 8,
 'Harley-Davidson': 9,
 'Kawasaki': 10,
 'Hyosung': 11,
 'Mahindra': 12,
 'Benelli': 13,
 'Triumph': 14,
 'Ducati': 15,
 'BMW': 16}

In [278]:
categorical["brand"]=categorical["brand"].map(dt2)
categorical["brand"]

0        6.0
1        2.0
2       14.0
3        6.0
4        5.0
        ...
9362     3.0
9369     1.0
9370     9.0
9371     1.0
9372     1.0
Name: brand, Length: 7324, dtype: float64

In [279]:
categorical.drop(["bike_name","owner","city"],axis="columns",inplace=True)

In [280]:
categorical

      brand
0       6.0
1       2.0
2      14.0
3       6.0
4       5.0
...     ...
9362    3.0
9369    1.0
9370    9.0
9371    1.0
9372    1.0

[7324 rows x 1 columns]

In [281]:
combined=pd.concat([categorical,numerical],axis=1)
combined

      brand     price  kms_driven  age  power
0       6.0   35000.0     17654.0  3.0  110.0
1       2.0  119900.0     11000.0  4.0  350.0
2      14.0  600000.0       110.0  8.0  675.0
3       6.0   65000.0     16329.0  4.0  180.0
4       5.0   80000.0     10000.0  3.0  150.0
...     ...       ...         ...  ...    ...
9362    3.0   25000.0     48587.0  8.0  150.0
9369    1.0   35000.0     60000.0  9.0  220.0
9370    9.0  450000.0      3430.0  4.0  750.0
9371    1.0  139000.0     21300.0  4.0  400.0
9372    1.0   80000.0      7127.0  5.0  220.0

[7324 rows x 5 columns]

In [282]:
combined.dropna(inplace=True)

In [283]:
# arrange data
x=combined.drop("price",axis=1)
x

      brand  kms_driven  age  power
0       6.0     17654.0  3.0  110.0
1       2.0     11000.0  4.0  350.0
2      14.0       110.0  8.0  675.0
3       6.0     16329.0  4.0  180.0
4       5.0     10000.0  3.0  150.0
...     ...         ...  ...    ...
9362    3.0     48587.0  8.0  150.0
9369    1.0     60000.0  9.0  220.0
9370    9.0      3430.0  4.0  750.0
9371    1.0     21300.0  4.0  400.0
9372    1.0      7127.0  5.0  220.0

[7307 rows x 4 columns]

In [284]:
y=combined[["price"]]
y

         price
0      35000.0
1     119900.0
2     600000.0
3      65000.0
4      80000.0
...        ...
9362   25000.0
9369   35000.0
9370  450000.0
9371  139000.0
9372   80000.0

[7307 rows x 1 columns]

In [285]:
# train test split 
# divide rows randomly in two parts train and test,ex= 80% and 20% of 1000 rows
# x_train , y_train ,x_test, y_test
#

In [287]:
from sklearn.model_selection import train_test_split

In [288]:
x_train  ,x_test,y_train, y_test=train_test_split(x,y,test_size=0.2)

In [289]:
# y_hat prediction is prediction given by algo
# in testing only x is given 
# in training x and y both are given 
#

In [290]:

from sklearn.linear_model import LinearRegression

In [291]:
# object of LinearRegression class
lg=LinearRegression()

In [292]:
x_train.isnull().sum()

brand         0
kms_driven    0
age           0
power         0
dtype: int64

In [294]:
x_train.head()

      brand  kms_driven   age  power
5348    1.0      3360.0   3.0  100.0
9316    3.0     28478.0   5.0  125.0
7857    2.0     16589.0   8.0  350.0
3384    1.0     30633.0  10.0  220.0
4779    1.0     45000.0  11.0  135.0

In [295]:
# linear regression algo training
# training data for training purpose
lg.fit(x_train,y_train)

LinearRegression()

In [296]:
# test model= model evaluation 
# model training  , measure the performance of model
# classification and regression both have diff method of evaluation
#

In [297]:
# training and testing
print("Training score :",round(lg.score(x_train,y_train)*100,2))
print("Testing score :",round(lg.score(x_test,y_test)*100,2))

Training score : 73.42
Testing score : 76.62

In [ ]:
# in above model

In [ ]:
# accuracy should be greater than 90
# diff btw training and testing score should not more than 5
# Is model overfit or underfit or perfect(generalized model)
# if model overfit = trainig score ---> high , testing score ---> low
# if model underfit = trainig score ---> low , testing score ---> high/low
# if generalized model = diff not more than 5 , model should not be overfit or underfit,score and accuracy should be high in both testing and training

In [298]:
# prediction --> pass x data to algo
y_hat=lg.predict(x_test)

In [299]:
x_test.shape

(1462, 4)

In [302]:
y_test["prediction"]=y_hat

In [303]:
y_test["prediction"]=y_test["prediction"].map(lambda x:round(x,2))

In [304]:
y_test.head(40)

         price  prediction
4609   32000.0     7135.78
5613   55000.0   101763.99
6247   45000.0    22943.63
4759   90000.0   133179.42
3838   54000.0    55855.02
6187  115000.0   128264.40
8415   55000.0    62543.18
1408   37000.0    64168.34
7966  140000.0   170787.11
91     75000.0    47858.50
847   120000.0   135712.76
7863   15995.0   -25769.97
95     60000.0    27566.24
5675   28000.0    62294.62
8206  126000.0   154621.08
2074  181200.0   227767.08
9143   15000.0    35227.02
7734   28000.0    10686.94
8512   32713.0    58926.64
2772   58000.0    44593.26
7378   76000.0    60280.69
8948  100000.0   209442.47
4049   28000.0    29460.46
4377   28000.0    12583.39
4162  130000.0   118988.30
4834  263000.0   230188.38
4892   20000.0    16070.25
4801  280000.0   393514.58
3025   27000.0    -4175.50
7748   67500.0    34632.09
8231   14200.0    -9448.48
158    50000.0    21193.55
8751   55000.0    49735.56
2888   23000.0     6592.90
5971  108000.0   136251.05
804   133700.0   144535.69
3127  107000.0   169974.53
8412   23000.0    28509.15
5153  125000.0   140942.29
8288   45000.0    39508.99

In [305]:
from sklearn.ensemble import RandomForestRegressor
rdf=RandomForestRegressor()

In [307]:
rdf.fit(x_train,y_train)

c:\Users\hp\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:1473: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

RandomForestRegressor()

In [312]:
print("Training score :",round(rdf.score(x_train,y_train)*100,2))
print("Testing score :",round(rdf.score(x_test,y_test["price"])*100,2))

Training score : 98.31
Testing score : 90.44

In [313]:
ls=["arushi","shalu","nikita","kartik"]
ls

['arushi', 'shalu', 'nikita', 'kartik']

In [314]:
import joblib

In [316]:
#  to save file permanently 
# dump in encrypted form
joblib.dump(ls,"favourite_student.lb")

['favourite_student.lb']

In [317]:
# to load or read file
#  in decrypted form
fav=joblib.load("favourite_student.lb")
fav

['arushi', 'shalu', 'nikita', 'kartik']

In [319]:
#  should not use lb for saving model file so that other can not find the type of the file
joblib.dump(lg,"linear_regression_model")

['linear_regression_model']